services:
  003-binance-staked-eth:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CLICKHOUSE_URL: http://clickhouse:8123
      CLICKHOUSE_DATABASE: wbeth
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    command: ["sh", "-lc", "node dist/index.js"]
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["with-pipeline"]

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_DB: wbeth
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-cors.xml:/etc/clickhouse-server/config.d/cors.xml:ro
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 3s
      timeout: 5s
      retries: 5


volumes:
  clickhouse-data:
