#!/bin/bash
set -e

# Creates a PR to subsquid-labs/agent-skills by applying a specific commit's
# diff to the upstream repo. Only the actual changes are applied — no install
# artifacts or formatting differences.
#
# Usage: ./scripts/pr-skill-patches.sh <commit-sha> "brief description"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMMIT="${1:?Usage: $0 <commit-sha> \"description\"}"
DESCRIPTION="${2:?Usage: $0 <commit-sha> \"description\"}"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH="ai-pipes-patch-${TIMESTAMP}"

cd "$REPO_ROOT"

# Verify the commit touches skill files
CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "$COMMIT" -- .agents/skills/ 2>/dev/null)
if [ -z "$CHANGED_FILES" ]; then
  echo "Commit $COMMIT has no changes to .agents/skills/. Nothing to PR."
  exit 0
fi

echo "Skill files changed in commit ${COMMIT:0:7}:"
echo "$CHANGED_FILES"
echo ""

# Generate a patch, rewriting paths from .agents/skills/ to upstream structure
# .agents/skills/pipes-* → pipes-sdk/pipes-*
# .agents/skills/portal-* → portal/portal-*
PATCH=$(git diff-tree --no-commit-id -p "$COMMIT" -- .agents/skills/)
REMAPPED_PATCH=$(echo "$PATCH" | sed \
  -e 's|a/\.agents/skills/pipes-|a/pipes-sdk/pipes-|g' \
  -e 's|b/\.agents/skills/pipes-|b/pipes-sdk/pipes-|g' \
  -e 's|a/\.agents/skills/portal-|a/portal/portal-|g' \
  -e 's|b/\.agents/skills/portal-|b/portal/portal-|g')

if [ -z "$REMAPPED_PATCH" ]; then
  echo "No patch content. Nothing to PR."
  exit 0
fi

# Clone the fork
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT
echo "Cloning karelxfi/agent-skills..."
gh repo clone karelxfi/agent-skills "$TMPDIR" -- --depth=1 -q
cd "$TMPDIR"
git checkout -b "$BRANCH"

# Apply the remapped patch
echo "$REMAPPED_PATCH" | git apply --3way 2>&1 || {
  echo "Patch failed to apply cleanly. May need manual intervention."
  echo "$REMAPPED_PATCH" | git apply --stat
  exit 1
}

if git diff --quiet && git diff --cached --quiet; then
  echo "Patch applied but no changes (already in upstream). Nothing to PR."
  exit 0
fi

echo "Applied patch:"
git diff --stat
echo ""

git add -A
git commit -m "fix: $DESCRIPTION

Source: https://github.com/karelxfi/ai-pipes/commit/$COMMIT"

git push origin "$BRANCH"

PR_URL=$(gh pr create \
  --repo subsquid-labs/agent-skills \
  --head "karelxfi:$BRANCH" \
  --title "fix: $DESCRIPTION" \
  --body "$(cat <<EOF
Patch from [ai-pipes](https://github.com/karelxfi/ai-pipes) indexer generation.

Source commit: [\`${COMMIT:0:7}\`](https://github.com/karelxfi/ai-pipes/commit/$COMMIT)

## Changes

$(git diff HEAD~1 --stat)

---
Generated by [ai-pipes](https://github.com/karelxfi/ai-pipes)
EOF
)")

echo ""
echo "PR created: $PR_URL"
