#!/bin/bash
set -e

# Creates a PR to subsquid-labs/agent-skills by applying a specific commit's
# diff to the LATEST upstream code. Syncs fork first to avoid stale PRs.
#
# Usage: ./scripts/pr-skill-patches.sh <commit-sha> "brief description"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMMIT="${1:?Usage: $0 <commit-sha> \"description\"}"
DESCRIPTION="${2:?Usage: $0 <commit-sha> \"description\"}"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH="ai-pipes-patch-${TIMESTAMP}"

cd "$REPO_ROOT"

# Verify the commit touches skill files
CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "$COMMIT" -- .agents/skills/ 2>/dev/null)
if [ -z "$CHANGED_FILES" ]; then
  echo "Commit $COMMIT has no changes to .agents/skills/. Nothing to PR."
  exit 0
fi

echo "Skill files changed in commit ${COMMIT:0:7}:"
echo "$CHANGED_FILES"
echo ""

# Step 1: Sync fork with upstream first
echo "Syncing fork with upstream..."
gh repo sync karelxfi/agent-skills --source subsquid-labs/agent-skills --force 2>&1 || {
  echo "Warning: fork sync failed. Continuing with potentially stale fork."
}

# Step 2: Clone the SYNCED fork
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT
echo "Cloning synced fork..."
gh repo clone karelxfi/agent-skills "$TMPDIR" -- --depth=1 -q
cd "$TMPDIR"
git checkout -b "$BRANCH"

# Step 3: For each changed file, apply ONLY the lines we added/changed
# Instead of applying a raw patch (which breaks on context diffs),
# we read our local version and the upstream version, and insert
# only the new content blocks.
APPLIED=0
while IFS= read -r file; do
  rel_path="${file#.agents/skills/}"
  skill_name="${rel_path%%/*}"
  file_in_skill="${rel_path#*/}"

  if [[ "$skill_name" == pipes-* ]]; then
    upstream_file="pipes-sdk/$skill_name/$file_in_skill"
  elif [[ "$skill_name" == portal-* ]]; then
    upstream_file="portal/$skill_name/$file_in_skill"
  else
    continue
  fi

  [ ! -f "$upstream_file" ] && continue

  # Get the diff for just this file from our commit
  FILE_PATCH=$(git -C "$REPO_ROOT" diff-tree --no-commit-id -p "$COMMIT" -- "$file" | sed \
    -e "s|a/$file|a/$upstream_file|g" \
    -e "s|b/$file|b/$upstream_file|g")

  if [ -z "$FILE_PATCH" ]; then
    continue
  fi

  # Try to apply. If context doesn't match (upstream changed), skip gracefully.
  if echo "$FILE_PATCH" | git apply --check 2>/dev/null; then
    echo "$FILE_PATCH" | git apply
    echo "  Applied: $upstream_file"
    APPLIED=$((APPLIED + 1))
  else
    # Try with fuzz
    if echo "$FILE_PATCH" | git apply --check -C0 2>/dev/null; then
      echo "$FILE_PATCH" | git apply -C0
      echo "  Applied (fuzzy): $upstream_file"
      APPLIED=$((APPLIED + 1))
    else
      echo "  SKIP: $upstream_file — patch conflicts with upstream changes (already addressed?)"
    fi
  fi
done <<< "$CHANGED_FILES"

if [ "$APPLIED" -eq 0 ]; then
  echo ""
  echo "No patches applied — upstream likely already has these changes."
  exit 0
fi

if git diff --quiet; then
  echo "No effective changes after applying patches."
  exit 0
fi

echo ""
echo "Changes to submit:"
git diff --stat
echo ""

git add -A
git commit -m "fix: $DESCRIPTION

Source: https://github.com/karelxfi/ai-pipes/commit/$COMMIT"

git push origin "$BRANCH"

PR_URL=$(gh pr create \
  --repo subsquid-labs/agent-skills \
  --head "karelxfi:$BRANCH" \
  --title "fix: $DESCRIPTION" \
  --body "$(cat <<EOF
Patch from [ai-pipes](https://github.com/karelxfi/ai-pipes) indexer generation.
Applied against latest upstream (fork synced before patching).

Source: [\`${COMMIT:0:7}\`](https://github.com/karelxfi/ai-pipes/commit/$COMMIT)

## Changes

$(git diff HEAD~1 --stat)

---
Generated by [ai-pipes](https://github.com/karelxfi/ai-pipes)
EOF
)")

echo ""
echo "PR created: $PR_URL"
