#!/bin/bash
set -e

# Creates a PR to subsquid-labs/agent-skills with ONLY the skill files
# that were intentionally modified during indexer generation.
#
# Usage: ./scripts/pr-skill-patches.sh "brief description of changes"
#
# How it works:
# 1. Checks git diff for .agents/skills/ — only files changed since last commit
# 2. If no changes, exits cleanly
# 3. Clones karelxfi/agent-skills fork
# 4. Copies ONLY the changed files into the upstream structure
# 5. Opens a PR to subsquid-labs/agent-skills

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DESCRIPTION="${1:?Usage: $0 \"brief description of changes\"}"
SKILLS_DIR="$REPO_ROOT/.agents/skills"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH="ai-pipes-patch-${TIMESTAMP}"

# Step 1: Find which skill files were actually changed
cd "$REPO_ROOT"
CHANGED_FILES=$(git diff --name-only HEAD -- .agents/skills/ 2>/dev/null)

if [ -z "$CHANGED_FILES" ]; then
  # Also check staged changes
  CHANGED_FILES=$(git diff --cached --name-only -- .agents/skills/ 2>/dev/null)
fi

if [ -z "$CHANGED_FILES" ]; then
  echo "No skill files were modified. Nothing to PR."
  exit 0
fi

echo "Changed skill files:"
echo "$CHANGED_FILES"
echo ""

# Step 2: Clone the fork
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT
echo "Cloning karelxfi/agent-skills..."
gh repo clone karelxfi/agent-skills "$TMPDIR" -- --depth=1 -q
cd "$TMPDIR"
git checkout -b "$BRANCH"

# Step 3: Copy ONLY the changed files, mapping to upstream paths
COPIED=0
while IFS= read -r file; do
  # file looks like: .agents/skills/pipes-new-indexer/SKILL.md
  # Strip .agents/skills/ prefix to get: pipes-new-indexer/SKILL.md
  rel_path="${file#.agents/skills/}"
  skill_name="${rel_path%%/*}"
  file_in_skill="${rel_path#*/}"

  # Map to upstream directory
  if [[ "$skill_name" == pipes-* ]]; then
    upstream_file="pipes-sdk/$skill_name/$file_in_skill"
  elif [[ "$skill_name" == portal-* ]]; then
    upstream_file="portal/$skill_name/$file_in_skill"
  else
    echo "  Skip: $rel_path (unknown skill category)"
    continue
  fi

  # Only copy if upstream file exists (don't create new files in upstream)
  upstream_dir=$(dirname "$upstream_file")
  if [ ! -d "$upstream_dir" ]; then
    echo "  Skip: $upstream_file (upstream dir doesn't exist)"
    continue
  fi

  cp "$REPO_ROOT/$file" "$upstream_file"
  echo "  Copy: $rel_path → $upstream_file"
  COPIED=$((COPIED + 1))
done <<< "$CHANGED_FILES"

if [ "$COPIED" -eq 0 ]; then
  echo "No files could be mapped to upstream. Nothing to PR."
  exit 0
fi

# Step 4: Check if there are actual content changes (not just formatting)
if git diff --quiet; then
  echo "Files were copied but content is identical to upstream. Nothing to PR."
  exit 0
fi

# Show what will be PR'd
echo ""
echo "Changes to submit:"
git diff --stat
echo ""
echo "Diff preview:"
git diff

# Step 5: Commit and push
git add -A
git commit -m "fix: $DESCRIPTION

Patches from building DeFi indexers in https://github.com/karelxfi/ai-pipes
Each change addresses a real issue encountered during indexer generation."

git push origin "$BRANCH"

# Step 6: Create PR
PR_URL=$(gh pr create \
  --repo subsquid-labs/agent-skills \
  --head "karelxfi:$BRANCH" \
  --title "fix: $DESCRIPTION" \
  --body "$(cat <<EOF
## Context

Patches from building real DeFi indexers in [ai-pipes](https://github.com/karelxfi/ai-pipes). Each change addresses a concrete issue encountered during generation.

## Changes

$(git diff HEAD~1 --stat)

---
Generated by [ai-pipes](https://github.com/karelxfi/ai-pipes)
EOF
)")

echo ""
echo "PR created: $PR_URL"
